name: Deploy

on:
    push:
        branches:
            - master
    # allow manual dispatch
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install dependencies
              working-directory: functions
              run: npm install

            - name: Build
              working-directory: functions
              run: npm run build

            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions
              env:
                  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
